# Neural Networks
Roksana Cieśla

In [5]:
import numpy as np
from keras.datasets import mnist
import keras
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

### Wczytanie i konwersja danych

In [9]:
training_set, test_set = mnist.load_data()

In [10]:
X_train, y_train = training_set
X_test, y_test = test_set

In [11]:
print(X_train.shape)

(60000, 28, 28)


In [12]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

In [13]:
print(X_train.shape)

(60000, 28, 28, 1)


In [15]:
X_train = X_train.astype(float) / 255.0  
X_test = X_test.astype(float) / 255.0

### Przygotowanie eksperymentu

In [16]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

In [17]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 10)                7850      
                                                                 
Total params: 7850 (30.66 KB)
Trainable params: 7850 (30.66 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

### Uczenie modelu

In [20]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 1s 1ms/step - loss: 0.7521 - accuracy: 0.8177 - val_loss: 0.4084 - val_accuracy: 0.8978
Epoch 2/30
375/375 [==============================] - 0s 802us/step - loss: 0.3892 - accuracy: 0.8973 - val_loss: 0.3341 - val_accuracy: 0.9113
Epoch 3/30
375/375 [==============================] - 0s 793us/step - loss: 0.3380 - accuracy: 0.9076 - val_loss: 0.3073 - val_accuracy: 0.9152
Epoch 4/30
375/375 [==============================] - 0s 778us/step - loss: 0.3143 - accuracy: 0.9133 - val_loss: 0.2933 - val_accuracy: 0.9185
Epoch 5/30
375/375 [==============================] - 0s 792us/step - loss: 0.3001 - accuracy: 0.9164 - val_loss: 0.2846 - val_accuracy: 0.9206
Epoch 6/30
375/375 [==============================] - 0s 797us/step - loss: 0.2907 - accuracy: 0.9196 - val_loss: 0.2802 - val_accuracy: 0.9224
Epoch 7/30
375/375 [==============================] - 0s 784us/step - loss: 0.2834 - accuracy: 0.9208 - val_loss: 0.2749 - val_accuracy: 0

### Ocena modelu

In [21]:
from sklearn.metrics import classification_report, confusion_matrix

In [22]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

313/313 [==============================] - 0s 381us/step


In [23]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.97      0.98      0.98      1135
           2       0.93      0.91      0.92      1032
           3       0.91      0.91      0.91      1010
           4       0.94      0.93      0.94       982
           5       0.90      0.88      0.89       892
           6       0.95      0.95      0.95       958
           7       0.94      0.92      0.93      1028
           8       0.88      0.90      0.89       974
           9       0.91      0.92      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 964    0    1    2    0    6    4    2    1    0]
 [   0 1114    3    3    0    1    3    2    9    0]
 [   4   10  935   15    6    3   11    8   37    3]
 [   3    0   19  923    0   24    2   11   22    6]
 [   1    1    7    1  913   

### Uczenie modeli nieliniowych

In [41]:
training_set, test_set = mnist.load_data()
X_train, y_train = training_set
X_test, y_test = test_set
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)
X_train = X_train.astype(int) / 255.0  
X_test = X_test.astype(int) / 255.0
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

In [42]:
model2 = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [43]:
model2.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_5 (Flatten)         (None, 784)               0         
                                                                 
 dense_13 (Dense)            (None, 64)                50240     
                                                                 
 dense_14 (Dense)            (None, 128)               8320      
                                                                 
 dense_15 (Dense)            (None, 10)                1290      
                                                                 
Total params: 59850 (233.79 KB)
Trainable params: 59850 (233.79 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [44]:
model2.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [45]:
model2.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 1s 2ms/step - loss: 0.4134 - accuracy: 0.8820 - val_loss: 0.2276 - val_accuracy: 0.9341
Epoch 2/30
375/375 [==============================] - 1s 1ms/step - loss: 0.1976 - accuracy: 0.9409 - val_loss: 0.1748 - val_accuracy: 0.9489
Epoch 3/30
375/375 [==============================] - 1s 1ms/step - loss: 0.1434 - accuracy: 0.9563 - val_loss: 0.1417 - val_accuracy: 0.9591
Epoch 4/30
375/375 [==============================] - 0s 1ms/step - loss: 0.1103 - accuracy: 0.9677 - val_loss: 0.1241 - val_accuracy: 0.9638
Epoch 5/30
375/375 [==============================] - 1s 1ms/step - loss: 0.0906 - accuracy: 0.9726 - val_loss: 0.1224 - val_accuracy: 0.9641
Epoch 6/30
375/375 [==============================] - 1s 1ms/step - loss: 0.0743 - accuracy: 0.9784 - val_loss: 0.1143 - val_accuracy: 0.9659
Epoch 7/30
375/375 [==============================] - 0s 1ms/step - loss: 0.0606 - accuracy: 0.9827 - val_loss: 0.1123 - val_accuracy: 0.9668
Epoch 

In [46]:
y_probab = model2.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

313/313 [==============================] - 0s 482us/step


In [47]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.97      0.97      1032
           3       0.95      0.98      0.96      1010
           4       0.98      0.97      0.97       982
           5       0.98      0.95      0.97       892
           6       0.97      0.98      0.98       958
           7       0.97      0.97      0.97      1028
           8       0.97      0.97      0.97       974
           9       0.98      0.96      0.97      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

[[ 969    0    2    2    2    0    3    1    1    0]
 [   0 1125    2    3    0    1    2    1    1    0]
 [   3    0 1006    4    2    0    3    5    9    0]
 [   0    0    7  986    1    5    0    4    2    5]
 [   0    0    1    1  956   

In [48]:
training_set, test_set = mnist.load_data()
X_train, y_train = training_set
X_test, y_test = test_set
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)
X_train = X_train.astype(int) / 255.0  
X_test = X_test.astype(int) / 255.0
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

In [50]:
model3 = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )

In [51]:
model3.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 13, 13, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_3 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_3 (MaxPoolin  (None, 5, 5, 64)          0         
 g2D)                                                            
                                                                 
 flatten_7 (Flatten)         (None, 1600)              0         
                                                                 
 dropout_1 (Dropout)         (None, 1600)             

In [52]:
model3.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [53]:
model3.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 12s 31ms/step - loss: 0.3970 - accuracy: 0.8795 - val_loss: 0.1119 - val_accuracy: 0.9681
Epoch 2/30
375/375 [==============================] - 12s 32ms/step - loss: 0.1199 - accuracy: 0.9629 - val_loss: 0.0719 - val_accuracy: 0.9798
Epoch 3/30
375/375 [==============================] - 13s 34ms/step - loss: 0.0883 - accuracy: 0.9717 - val_loss: 0.0569 - val_accuracy: 0.9835
Epoch 4/30
375/375 [==============================] - 13s 33ms/step - loss: 0.0736 - accuracy: 0.9772 - val_loss: 0.0517 - val_accuracy: 0.9841
Epoch 5/30
375/375 [==============================] - 12s 31ms/step - loss: 0.0631 - accuracy: 0.9806 - val_loss: 0.0502 - val_accuracy: 0.9862
Epoch 6/30
375/375 [==============================] - 12s 32ms/step - loss: 0.0589 - accuracy: 0.9814 - val_loss: 0.0417 - val_accuracy: 0.9883
Epoch 7/30
375/375 [==============================] - 12s 32ms/step - loss: 0.0532 - accuracy: 0.9840 - val_loss: 0.0432 - val_accuracy:

In [54]:
y_probab = model3.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

313/313 [==============================] - 1s 3ms/step


In [55]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       1.00      0.99      0.99      1135
           2       0.99      1.00      0.99      1032
           3       0.99      0.99      0.99      1010
           4       0.99      0.99      0.99       982
           5       0.99      0.99      0.99       892
           6       0.99      0.99      0.99       958
           7       0.99      0.99      0.99      1028
           8       0.99      0.99      0.99       974
           9       0.99      0.99      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

[[ 979    0    0    0    0    0    0    1    0    0]
 [   0 1126    3    3    1    0    2    0    0    0]
 [   1    0 1029    0    0    0    0    2    0    0]
 [   0    0    1 1004    0    3    0    1    1    0]
 [   0    0    0    0  976   